export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS";
export const PRODUCTS_DOWNLOAD_ERROR = "PRODUCTS_DOWNLOAD_ERROR";

export const GET_PRODUCT_REMOVE = "GET_PRODUCT_REMOVE";
export const PRODUCT_REMOVED_SUCCESS = "PRODUCT_REMOVED_SUCCESS";
export const PRODUCT_REMOVED_ERROR = "PRODUCT_REMOVED_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_PRODUCT_EDIT = "START_PRODUCT_EDIT";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
